//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actual_cropcutting_exercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actual_cropcutting_exercise()
        {
            this.cce_queue_farms = new HashSet<cce_queue_farms>();
        }
    
        public int id { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> county { get; set; }
        public Nullable<int> sub_county { get; set; }
        public Nullable<int> ward { get; set; }
        public Nullable<int> cropacreage { get; set; }
        public string enumeration_area_code { get; set; }
        public string village_name { get; set; }
        public string respondent_name { get; set; }
        public string respondent_telephone { get; set; }
        public string respondent_relation { get; set; }
        public string date_of_crop_cutting { get; set; }
        public string time_of_cropcutting_start { get; set; }
        public string time_of_cropcutting_end { get; set; }
        public Nullable<int> total_count_maizeplants_inSS { get; set; }
        public Nullable<int> total_count_cobs_inSS { get; set; }
        public Nullable<int> total_count_plants_stage1 { get; set; }
        public Nullable<int> total_count_plants_stage2 { get; set; }
        public Nullable<int> total_cobs_stage1 { get; set; }
        public Nullable<int> total_cobs_stage2 { get; set; }
        public string photo_ofSS_before_harvesting { get; set; }
        public Nullable<int> cobs_harvested { get; set; }
        public Nullable<decimal> quantity_harvested_wetgrain { get; set; }
        public Nullable<decimal> quantity_harvested_kgpercob { get; set; }
        public string final_quantity_wetgrain { get; set; }
        public Nullable<decimal> moisture_reading { get; set; }
        public string quantity_wet_sample { get; set; }
        public string video_taken_CCE { get; set; }
        public string drying_method { get; set; }
        public Nullable<decimal> weight_of_wetsample { get; set; }
        public Nullable<decimal> weight_of_driedsample { get; set; }
        public Nullable<decimal> total_weight { get; set; }
        public Nullable<decimal> moisture_percentagedried { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    
        public virtual county county1 { get; set; }
        public virtual subcounty subcounty { get; set; }
        public virtual ward ward1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cce_queue_farms> cce_queue_farms { get; set; }
        public virtual farm_actual_cropcutting_exercise farm_actual_cropcutting_exercise { get; set; }
    }
}
