//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adimsEntities : DbContext
    {
        public adimsEntities()
            : base("name=adimsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actual_cropcutting_exercise> actual_cropcutting_exercise { get; set; }
        public virtual DbSet<auditlog> auditlogs { get; set; }
        public virtual DbSet<ayii_policy> ayii_policy { get; set; }
        public virtual DbSet<cce_queue_farms> cce_queue_farms { get; set; }
        public virtual DbSet<claimrequest> claimrequests { get; set; }
        public virtual DbSet<county> counties { get; set; }
        public virtual DbSet<county_weather_data> county_weather_data { get; set; }
        public virtual DbSet<crop> crops { get; set; }
        public virtual DbSet<crop_cutting_queue> crop_cutting_queue { get; set; }
        public virtual DbSet<crop_production_statistics> crop_production_statistics { get; set; }
        public virtual DbSet<cropacreage> cropacreages { get; set; }
        public virtual DbSet<cropvariety> cropvarieties { get; set; }
        public virtual DbSet<disaster_warning_data> disaster_warning_data { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<early_warning> early_warning { get; set; }
        public virtual DbSet<farm> farms { get; set; }
        public virtual DbSet<farm_actual_cropcutting_exercise> farm_actual_cropcutting_exercise { get; set; }
        public virtual DbSet<farm_policy> farm_policy { get; set; }
        public virtual DbSet<farm_policy_premium> farm_policy_premium { get; set; }
        public virtual DbSet<farm_preliminary_cropcutting_exercise> farm_preliminary_cropcutting_exercise { get; set; }
        public virtual DbSet<farmcoordinate> farmcoordinates { get; set; }
        public virtual DbSet<farmer> farmers { get; set; }
        public virtual DbSet<farmer_insurance> farmer_insurance { get; set; }
        public virtual DbSet<farmer_photo> farmer_photo { get; set; }
        public virtual DbSet<farmingmethod> farmingmethods { get; set; }
        public virtual DbSet<fertilizer> fertilizers { get; set; }
        public virtual DbSet<foodstocks_data> foodstocks_data { get; set; }
        public virtual DbSet<govt_subsidized_fertilizer> govt_subsidized_fertilizer { get; set; }
        public virtual DbSet<input_cost_and_availability> input_cost_and_availability { get; set; }
        public virtual DbSet<insurance_company> insurance_company { get; set; }
        public virtual DbSet<photo> photos { get; set; }
        public virtual DbSet<planting_fertilizer> planting_fertilizer { get; set; }
        public virtual DbSet<plantingmethod> plantingmethods { get; set; }
        public virtual DbSet<preliminary_cropcutting_exercise> preliminary_cropcutting_exercise { get; set; }
        public virtual DbSet<premium_rate> premium_rate { get; set; }
        public virtual DbSet<price_trend> price_trend { get; set; }
        public virtual DbSet<season> seasons { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<soiltype> soiltypes { get; set; }
        public virtual DbSet<subcounty> subcounties { get; set; }
        public virtual DbSet<top_dressing_fertilizer> top_dressing_fertilizer { get; set; }
        public virtual DbSet<uai> uais { get; set; }
        public virtual DbSet<uai_variables> uai_variables { get; set; }
        public virtual DbSet<uai_yield> uai_yield { get; set; }
        public virtual DbSet<unitofmeasure> unitofmeasures { get; set; }
        public virtual DbSet<ward> wards { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<cce_actual_progress> cce_actual_progress { get; set; }
        public virtual DbSet<cce_pre_progress> cce_pre_progress { get; set; }
        public virtual DbSet<farmer_corp_progress> farmer_corp_progress { get; set; }
        public virtual DbSet<farmer_grp_progress> farmer_grp_progress { get; set; }
        public virtual DbSet<farmer_ind_progress> farmer_ind_progress { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
