//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ayii_policy
    {
        public int id { get; set; }
        public string ayii_policy_no { get; set; }
        public Nullable<int> farmer { get; set; }
        public Nullable<int> cropacreage { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> uai { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    
        public virtual cropacreage cropacreage1 { get; set; }
        public virtual farmer farmer1 { get; set; }
        public virtual season season1 { get; set; }
        public virtual uai uai1 { get; set; }
    }
}
