//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claimrequest
    {
        public int id { get; set; }
        public Nullable<int> farmid { get; set; }
        public Nullable<int> farm_policyid { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public Nullable<double> amount { get; set; }
        public string channel { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> createdby { get; set; }
    
        public virtual farm farm { get; set; }
        public virtual farm_policy farm_policy { get; set; }
    }
}
