//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop_production_statistics
    {
        public int id { get; set; }
        public Nullable<int> county { get; set; }
        public Nullable<int> sub_county { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> no_sampled_ls_farms { get; set; }
        public Nullable<int> no_sampled_ci_farms { get; set; }
        public Nullable<int> no_sampled_irrigation_schemes { get; set; }
        public Nullable<int> no_sampled_greenhouses { get; set; }
        public Nullable<int> no_ss_farms { get; set; }
        public Nullable<int> core_crop { get; set; }
        public Nullable<double> hectares_planted { get; set; }
        public Nullable<int> estimated_ha_certified_seeds { get; set; }
        public Nullable<double> estimated_seed_quantity { get; set; }
    
        public virtual county county1 { get; set; }
        public virtual season season1 { get; set; }
        public virtual subcounty subcounty { get; set; }
    }
}
