//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cropacreage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cropacreage()
        {
            this.ayii_policy = new HashSet<ayii_policy>();
            this.cce_queue_farms = new HashSet<cce_queue_farms>();
            this.farm_actual_cropcutting_exercise = new HashSet<farm_actual_cropcutting_exercise>();
            this.farm_preliminary_cropcutting_exercise = new HashSet<farm_preliminary_cropcutting_exercise>();
        }
    
        public int id { get; set; }
        public Nullable<int> farmid { get; set; }
        public Nullable<int> cropid { get; set; }
        public Nullable<int> variety { get; set; }
        public Nullable<double> acreage { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ayii_policy> ayii_policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cce_queue_farms> cce_queue_farms { get; set; }
        public virtual crop crop { get; set; }
        public virtual cropvariety cropvariety { get; set; }
        public virtual farm farm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farm_actual_cropcutting_exercise> farm_actual_cropcutting_exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farm_preliminary_cropcutting_exercise> farm_preliminary_cropcutting_exercise { get; set; }
    }
}
