//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop_cutting_queue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crop_cutting_queue()
        {
            this.cce_queue_farms = new HashSet<cce_queue_farms>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> county { get; set; }
        public Nullable<int> sub_county { get; set; }
        public Nullable<int> ward { get; set; }
        public Nullable<int> uai { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> total_status { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cce_queue_farms> cce_queue_farms { get; set; }
        public virtual county county1 { get; set; }
        public virtual season season1 { get; set; }
        public virtual subcounty subcounty { get; set; }
        public virtual ward ward1 { get; set; }
        public virtual uai uai1 { get; set; }
    }
}
