//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crop()
        {
            this.cropacreages = new HashSet<cropacreage>();
            this.cropvarieties = new HashSet<cropvariety>();
            this.farm_policy = new HashSet<farm_policy>();
            this.preliminary_cropcutting_exercise = new HashSet<preliminary_cropcutting_exercise>();
            this.uai_yield = new HashSet<uai_yield>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
        public string localnames { get; set; }
        public Nullable<int> maturityperiod { get; set; }
        public Nullable<int> unitmeasure { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> plantingmethod { get; set; }
    
        public virtual plantingmethod plantingmethod1 { get; set; }
        public virtual unitofmeasure unitofmeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cropacreage> cropacreages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cropvariety> cropvarieties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farm_policy> farm_policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preliminary_cropcutting_exercise> preliminary_cropcutting_exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uai_yield> uai_yield { get; set; }
    }
}
