//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farm_preliminary_cropcutting_exercise
    {
        public int id { get; set; }
        public Nullable<int> cropacreage { get; set; }
        public Nullable<int> preliminary_cropcutting_exercise { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    
        public virtual cropacreage cropacreage1 { get; set; }
        public virtual preliminary_cropcutting_exercise preliminary_cropcutting_exercise1 { get; set; }
        public virtual season season1 { get; set; }
    }
}
