//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farm_policy_premium
    {
        public int id { get; set; }
        public Nullable<int> farm_policy_id { get; set; }
        public Nullable<int> farmer { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    
        public virtual farm_policy farm_policy { get; set; }
        public virtual farmer farmer1 { get; set; }
    }
}
