//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farm_policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public farm_policy()
        {
            this.claimrequests = new HashSet<claimrequest>();
            this.farm_policy_premium = new HashSet<farm_policy_premium>();
        }
    
        public int id { get; set; }
        public Nullable<int> farmid { get; set; }
        public string policy_number { get; set; }
        public Nullable<int> insurance_companyid { get; set; }
        public string uai_name { get; set; }
        public Nullable<int> cropinsured { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<double> preferred_coverage { get; set; }
        public Nullable<System.DateTime> dateofpolicysale { get; set; }
        public Nullable<double> average_yield { get; set; }
        public Nullable<double> insured_yield { get; set; }
        public Nullable<double> sum_insured { get; set; }
        public Nullable<double> area_insured { get; set; }
        public Nullable<double> total_insured { get; set; }
        public Nullable<double> premium_rate { get; set; }
        public Nullable<double> total_premium { get; set; }
        public Nullable<double> subsidy_amount { get; set; }
        public Nullable<double> final_premium { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claimrequest> claimrequests { get; set; }
        public virtual crop crop { get; set; }
        public virtual farm farm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farm_policy_premium> farm_policy_premium { get; set; }
        public virtual insurance_company insurance_company { get; set; }
    }
}
