//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmer_photo
    {
        public int id { get; set; }
        public Nullable<int> farmerid { get; set; }
        public Nullable<int> photoid { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> createdby { get; set; }
    
        public virtual farmer farmer { get; set; }
        public virtual photo photo { get; set; }
    }
}
