//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmer_insurance
    {
        public int id { get; set; }
        public Nullable<int> farmer { get; set; }
        public string insurance_type { get; set; }
        public string other_insurance { get; set; }
        public string insurer { get; set; }
        public string crop { get; set; }
        public string policy_number { get; set; }
    
        public virtual farmer farmer1 { get; set; }
    }
}
