//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class farm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public farm()
        {
            this.claimrequests = new HashSet<claimrequest>();
            this.cropacreages = new HashSet<cropacreage>();
            this.farmcoordinates = new HashSet<farmcoordinate>();
            this.farm_policy = new HashSet<farm_policy>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> farmerid { get; set; }
        public Nullable<double> area { get; set; }
        public Nullable<int> countyid { get; set; }
        public Nullable<int> wardid { get; set; }
        public Nullable<int> soiltype { get; set; }
        public string lrnumber { get; set; }
        public string topography { get; set; }
        public string aez { get; set; }
        public string status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> farmingmethod { get; set; }
        public string irrigationMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claimrequest> claimrequests { get; set; }
        public virtual county county { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cropacreage> cropacreages { get; set; }
        public virtual farmer farmer { get; set; }
        public virtual farmingmethod farmingmethod1 { get; set; }
        public virtual soiltype soiltype1 { get; set; }
        public virtual ward ward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farmcoordinate> farmcoordinates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<farm_policy> farm_policy { get; set; }
    }
}
