//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodstocks_data
    {
        public int id { get; set; }
        public Nullable<int> county { get; set; }
        public Nullable<int> sub_county { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> season { get; set; }
        public string commodity { get; set; }
        public Nullable<int> total_sampled_farmers { get; set; }
        public Nullable<int> total_sampled_traders { get; set; }
        public Nullable<int> total_sampled_millers { get; set; }
        public Nullable<int> total_ncpb_depots { get; set; }
        public Nullable<int> total_food_aid_agencies { get; set; }
        public Nullable<int> farmer_bags { get; set; }
        public Nullable<int> trader_bags { get; set; }
        public Nullable<int> miller_bags { get; set; }
        public Nullable<int> ncpb_bags { get; set; }
        public Nullable<int> food_aid_bags { get; set; }
    
        public virtual county county1 { get; set; }
        public virtual season season1 { get; set; }
        public virtual subcounty subcounty { get; set; }
    }
}
