//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class input_cost_and_availability
    {
        public int id { get; set; }
        public Nullable<int> county { get; set; }
        public Nullable<int> sub_county { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> no_sampled_stoclist { get; set; }
        public Nullable<int> nno_sampled_ncpb_stores { get; set; }
        public string type_of_input { get; set; }
        public string unit { get; set; }
        public Nullable<int> crop_condition { get; set; }
        public Nullable<double> lowest_retail_price { get; set; }
        public Nullable<double> highest_retail_price { get; set; }
        public Nullable<int> availability { get; set; }
    
        public virtual county county1 { get; set; }
        public virtual season season1 { get; set; }
        public virtual subcounty subcounty { get; set; }
    }
}
