//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcounty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subcounty()
        {
            this.actual_cropcutting_exercise = new HashSet<actual_cropcutting_exercise>();
            this.county_weather_data = new HashSet<county_weather_data>();
            this.crop_cutting_queue = new HashSet<crop_cutting_queue>();
            this.crop_production_statistics = new HashSet<crop_production_statistics>();
            this.disaster_warning_data = new HashSet<disaster_warning_data>();
            this.early_warning = new HashSet<early_warning>();
            this.foodstocks_data = new HashSet<foodstocks_data>();
            this.govt_subsidized_fertilizer = new HashSet<govt_subsidized_fertilizer>();
            this.input_cost_and_availability = new HashSet<input_cost_and_availability>();
            this.planting_fertilizer = new HashSet<planting_fertilizer>();
            this.preliminary_cropcutting_exercise = new HashSet<preliminary_cropcutting_exercise>();
            this.price_trend = new HashSet<price_trend>();
            this.top_dressing_fertilizer = new HashSet<top_dressing_fertilizer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<int> countyid { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actual_cropcutting_exercise> actual_cropcutting_exercise { get; set; }
        public virtual county county { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<county_weather_data> county_weather_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_cutting_queue> crop_cutting_queue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crop_production_statistics> crop_production_statistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disaster_warning_data> disaster_warning_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<early_warning> early_warning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foodstocks_data> foodstocks_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<govt_subsidized_fertilizer> govt_subsidized_fertilizer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<input_cost_and_availability> input_cost_and_availability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<planting_fertilizer> planting_fertilizer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preliminary_cropcutting_exercise> preliminary_cropcutting_exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<price_trend> price_trend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<top_dressing_fertilizer> top_dressing_fertilizer { get; set; }
    }
}
