//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uai_yield
    {
        public int id { get; set; }
        public Nullable<int> crop { get; set; }
        public Nullable<int> ward { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<double> average_yield { get; set; }
    
        public virtual crop crop1 { get; set; }
        public virtual season season1 { get; set; }
        public virtual ward ward1 { get; set; }
    }
}
