//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uai_variables
    {
        public int id { get; set; }
        public Nullable<int> uai { get; set; }
        public Nullable<double> historical_average { get; set; }
        public Nullable<double> average_yield { get; set; }
        public Nullable<double> coverage { get; set; }
        public Nullable<double> unitvalue { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual uai uai1 { get; set; }
        public virtual season season1 { get; set; }
    }
}
