// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ADIMSTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test to Add a Farmer on Adims
        /// </summary>
        public void AddFarmerTest()
        {
            #region Variable Declarations
            WinWindow uIADIMSLoginGoogleChroWindow1 = this.UIADIMSLoginGoogleChroWindow.UIADIMSLoginGoogleChroWindow1;
            WinControl uIADIMSLoginGoogleChroDocument = this.UIADIMSLoginGoogleChroWindow.UIChromeLegacyWindowWindow.UIADIMSLoginGoogleChroDocument;
            WinWindow uIM_EditorWindow = this.UISQLQuery3sqlERNESTadWindow.UIItemWindow.UISqlScriptEditorContrClient.UIM_EditorWindow;
            WinWindow uIItemWindow = this.UIItemWindow.UIItemWindow1.UIItemWindow;
            WinWindow uIItemWindow1 = this.UIItemWindow.UIItemWindow2.UIItemWindow;
            #endregion

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1887, 323));

            // Type 'ernest{LShiftKey}@miyabiafrica.com' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys, ModifierKeys.None);

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1868, 386));

            // Type 'Realnigga99{LShiftKey}{#}' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys1, ModifierKeys.None);

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1776, 500));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(796, 384));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(746, 426));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1047, 482));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1103, 500));

            // Type 'Ernest{Tab}{LShiftKey}John{Tab}{LShiftKey}Ndungu' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys2, ModifierKeys.None);

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2137, 424));

            // Click window
            Mouse.Click(uIItemWindow, new Point(755, 7));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2408, 421));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2386, 464));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1103, 646));

            // Type '0710148737' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys3, ModifierKeys.None);

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2367, 517));

            // Move 'ADIMS - Login - Google Chrome' window
            Mouse.StartDragging(uIADIMSLoginGoogleChroWindow1, new Point(1683, 306));
            Mouse.StopDragging(uIADIMSLoginGoogleChroWindow1, -13, 284);

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2398, 362));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(2069, 771));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1036, 484));

            // Type '30014896' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys4, ModifierKeys.None);

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2379, 347));

            // Type 'A2998798{Tab}' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys5, ModifierKeys.None);

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1781, 495));

            // Type 'P3269' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys6, ModifierKeys.None);

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(2057, 775));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1097, 500));

            // Type 'Cajuna' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys7, ModifierKeys.None);

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2417, 357));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2418, 408));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(2068, 777));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2126, 349));

            // Type 'Chuom {LShiftKey}Fulani' in 'ADIMS - Login - Google Chrome' document
            Keyboard.SendKeys(uIADIMSLoginGoogleChroDocument, this.AddFarmerTestParams.UIADIMSLoginGoogleChroDocumentSendKeys8, ModifierKeys.None);

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2106, 424));

            // Click window
            Mouse.Click(uIItemWindow, new Point(743, 98));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2393, 444));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2394, 535));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1873, 576));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1807, 686));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(2072, 770));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2267, 331));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2241, 369));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(1105, 559));

            // Click window
            Mouse.Click(uIItemWindow1, new Point(742, 23));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2518, 414));

            // Click 'm_Editor' window
            Mouse.Click(uIM_EditorWindow, new Point(2445, 438));

            // Click 'ADIMS - Login - Google Chrome' window
            Mouse.Click(uIADIMSLoginGoogleChroWindow1, new Point(2129, 770));
        }
        
        #region Properties
        public virtual AddFarmerTestParams AddFarmerTestParams
        {
            get
            {
                if ((this.mAddFarmerTestParams == null))
                {
                    this.mAddFarmerTestParams = new AddFarmerTestParams();
                }
                return this.mAddFarmerTestParams;
            }
        }
        
        public UIADIMSLoginGoogleChroWindow UIADIMSLoginGoogleChroWindow
        {
            get
            {
                if ((this.mUIADIMSLoginGoogleChroWindow == null))
                {
                    this.mUIADIMSLoginGoogleChroWindow = new UIADIMSLoginGoogleChroWindow();
                }
                return this.mUIADIMSLoginGoogleChroWindow;
            }
        }
        
        public UISQLQuery3sqlERNESTadWindow UISQLQuery3sqlERNESTadWindow
        {
            get
            {
                if ((this.mUISQLQuery3sqlERNESTadWindow == null))
                {
                    this.mUISQLQuery3sqlERNESTadWindow = new UISQLQuery3sqlERNESTadWindow();
                }
                return this.mUISQLQuery3sqlERNESTadWindow;
            }
        }
        
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private AddFarmerTestParams mAddFarmerTestParams;
        
        private UIADIMSLoginGoogleChroWindow mUIADIMSLoginGoogleChroWindow;
        
        private UISQLQuery3sqlERNESTadWindow mUISQLQuery3sqlERNESTadWindow;
        
        private UIItemWindow3 mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddFarmerTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AddFarmerTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'ernest{LShiftKey}@miyabiafrica.com' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys = "ernest{LShiftKey}@miyabiafrica.com";
        
        /// <summary>
        /// Type 'Realnigga99{LShiftKey}{#}' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys1 = "Realnigga99{LShiftKey}{#}";
        
        /// <summary>
        /// Type 'Ernest{Tab}{LShiftKey}John{Tab}{LShiftKey}Ndungu' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys2 = "Ernest{Tab}{LShiftKey}John{Tab}{LShiftKey}Ndungu";
        
        /// <summary>
        /// Type '0710148737' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys3 = "0710148737";
        
        /// <summary>
        /// Type '30014896' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys4 = "30014896";
        
        /// <summary>
        /// Type 'A2998798{Tab}' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys5 = "A2998798{Tab}";
        
        /// <summary>
        /// Type 'P3269' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys6 = "P3269";
        
        /// <summary>
        /// Type 'Cajuna' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys7 = "Cajuna";
        
        /// <summary>
        /// Type 'Chuom {LShiftKey}Fulani' in 'ADIMS - Login - Google Chrome' document
        /// </summary>
        public string UIADIMSLoginGoogleChroDocumentSendKeys8 = "Chuom {LShiftKey}Fulani";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIADIMSLoginGoogleChroWindow : WinWindow
    {
        
        public UIADIMSLoginGoogleChroWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ADIMS - Login - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("ADIMS - Login - Google Chrome");
            this.WindowTitles.Add("ADIMS - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UIADIMSLoginGoogleChroWindow1
        {
            get
            {
                if ((this.mUIADIMSLoginGoogleChroWindow1 == null))
                {
                    this.mUIADIMSLoginGoogleChroWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUIADIMSLoginGoogleChroWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "ADIMS - Login";
                    this.mUIADIMSLoginGoogleChroWindow1.WindowTitles.Add("ADIMS - Login - Google Chrome");
                    this.mUIADIMSLoginGoogleChroWindow1.WindowTitles.Add("ADIMS - Google Chrome");
                    #endregion
                }
                return this.mUIADIMSLoginGoogleChroWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIADIMSLoginGoogleChroWindow1;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("ADIMS - Login - Google Chrome");
            this.WindowTitles.Add("ADIMS - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIADIMSLoginGoogleChroDocument
        {
            get
            {
                if ((this.mUIADIMSLoginGoogleChroDocument == null))
                {
                    this.mUIADIMSLoginGoogleChroDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIADIMSLoginGoogleChroDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIADIMSLoginGoogleChroDocument.WindowTitles.Add("ADIMS - Login - Google Chrome");
                    this.mUIADIMSLoginGoogleChroDocument.WindowTitles.Add("ADIMS - Google Chrome");
                    #endregion
                }
                return this.mUIADIMSLoginGoogleChroDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIADIMSLoginGoogleChroDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISQLQuery3sqlERNESTadWindow : WinWindow
    {
        
        public UISQLQuery3sqlERNESTadWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SQLQuery3.sql - ERNEST.adims (ERNEST\\ernjo (56)) - Microsoft SQL Server Managemen" +
                "t Studio";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("SQLQuery3.sql - ERNEST.adims (ERNEST\\ernjo (56)) - Microsoft SQL Server Managemen" +
                    "t Studio");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("SQLQuery3.sql - ERNEST.adims (ERNEST\\ernjo (56)) - Microsoft SQL Server Managemen" +
                    "t Studio");
            #endregion
        }
        
        #region Properties
        public UISqlScriptEditorContrClient UISqlScriptEditorContrClient
        {
            get
            {
                if ((this.mUISqlScriptEditorContrClient == null))
                {
                    this.mUISqlScriptEditorContrClient = new UISqlScriptEditorContrClient(this);
                }
                return this.mUISqlScriptEditorContrClient;
            }
        }
        #endregion
        
        #region Fields
        private UISqlScriptEditorContrClient mUISqlScriptEditorContrClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISqlScriptEditorContrClient : WinClient
    {
        
        public UISqlScriptEditorContrClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("SQLQuery3.sql - ERNEST.adims (ERNEST\\ernjo (56)) - Microsoft SQL Server Managemen" +
                    "t Studio");
            #endregion
        }
        
        #region Properties
        public WinWindow UIM_EditorWindow
        {
            get
            {
                if ((this.mUIM_EditorWindow == null))
                {
                    this.mUIM_EditorWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIM_EditorWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIM_EditorWindow.WindowTitles.Add("SQLQuery3.sql - ERNEST.adims (ERNEST\\ernjo (56)) - Microsoft SQL Server Managemen" +
                            "t Studio");
                    #endregion
                }
                return this.mUIM_EditorWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIM_EditorWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        
        private UIItemWindow2 mUIItemWindow2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItemWindow.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    #endregion
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItemWindow.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    #endregion
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItemWindow;
        #endregion
    }
}
